#!/bin/bash
#
# plot radial anisotropy factors, use chi. global, simple version
# 
models=${1-"safs417nc safs417nc_er pmDsmean_nt safs4 med_weak_mix_nsmit med_weak_mix_ns2 med_weak_mix_ns3 med_weak_mix_ns2e2  med_weak_mix_ns2e2k med_weak_mix_ns2e  med_weak_mix_ns2e3 med_weak_mix_ns2e3k "}
strain=${2-0.75}
#depths=${3-"50 150 250"}
depths=${3-"100 200 300"}
gv=${4-0}

remove_mean=0			# remove the regional mean anisotropy?


lmax=20				# smoothing
#lmax=31				# smoothing

tfhw=10				# exp half width for model damping

#grdimage="grdimage -nl"
grdimage="grdimage"

tmpn=/tmp/$USER.$HOST.nnr.$$.tnr
trap "rm -f $tmpn.* ; exit" 0 1 2  15

reg=-Rg
pscr="-Dc -A100000" # pscoast
#ann=`region_parameters $rcode 6` # annotation
#ann=-Ba20f1/a10f1
ann=""
#proj=`region_parameters $rcode 4` # projection
#proj=-JH0/5
proj=-JH180/5


#makecpt -T.875/1.125/0.0025 -Chaxby  -I -D > chi.cpt
#makecpt -T-.15/0.15/0.001 -Chaxby  -I -D > dchi.cpt
makecpt -T.875/1.15/0.025 -Croma  -I -D > chi.cpt
makecpt -T-.15/0.15/0.01 -Croma  -I -D > dchi.cpt


gmtset BASEMAP_TYPE plain

for model in $models;do


    dx=0.5
    inc=-I$dx

    dc=1
	
    for depth in $depths;do

	.  $HOME/CITCOM/fulltest/name_med
	echo model $model depth $depth strain $strain $title
	#
	# rphi version
	#
	file=$model/results/tracer.rphid.0.$depth.s.$strain.dat.gz
	if [ ! -s $file ];then
	    file=$model/results/tracer.er.rphid.0.$depth.s.$strain.dat.gz
	    if [ ! -s $file ];then
		echo $0: file $model/results/tracer.er.rphid.0.$depth.s.$strain.dat.gz
		echo $0: $model/results/tracer.rphid.0.$depth.s.$strain.dat.gz and not found
		ls $model/results/tracer.*rphid.0.*.s.$strain.dat.gz
		exit
	    fi
	fi
	echo $0: using $file
	#
	# model
	#
	rm model.$depth.grd 2> /dev/null
        #  chi = N/L = (v_{SH}/v_{SH})^2
	#zcat $file | gawk '{print($1,$2,$5/$4)}' | surface -fg $reg $inc -Gtmp.$$.grd
	zcat $file | gawk '{print($1,$2,$5/$4)}' | sphinterpolate -Q2 -fg $reg $inc -Gtmp.$$.grd
	if [ $remove_mean -eq 1 ];then
	    mean=`grd2geo_mean tmp.$$.grd`
	    grdmath tmp.$$.grd $mean SUB = model.$depth.grd
	    cmp=dchi.cpt
	else
	    cp tmp.$$.grd model.$depth.grd
	    cmp=chi.cpt
	fi
	rm tmp.$$.grd


	
	
	ofile=$HOME/tmp/$model.s.$strain.eps

	if [ $dc -eq 1 ];then
	    $grdimage model.$depth.grd -C$cmp $reg $proj -Y7 -X0.2  -P -K > $ofile
	else
	    $grdimage model.$depth.grd -C$cmp $reg $proj -Y-2.75  -O -K >> $ofile
	fi
	if [ $dc -eq 1 ];then
	    echo -0.1 0.92 20 0 31 ML "$title" | pstext -R0/1/0/1 -JX3.  -O -N -K >> $ofile
	fi
	echo 1.75 0.8 18 0 29 MC "$depth km" | pstext -R0/1/0/1 -JX3.  -O -N -K >> $ofile

	pscoast $pscr -W2,128 $reg $proj -O -K >> $ofile
	psxy $datadir/plate_boundaries/nuvel_without_greenwich_crossing.yx -m -: \
	    $reg  $proj  -O -K   -W1,darkgreen  >> $ofile

	if [ $dc -eq 3 ];then
	    if [ $remove_mean -eq 1 ];then
		psscale -Dx2.7/-.25/3/.2h -B.05/:"@~dx@~": -O -E -K -C$cmp >> $ofile
	    else
		psscale -Dx2.7/-.25/3/.2h -B.05/:"@~x@~": -O -E -K -C$cmp >> $ofile
	    fi
	fi

        ((dc=dc+1))

    done
    echo 1000 1000 | psxy $reg $proj -O >> $ofile

    modifybb $ofile 2> /dev/null
    #    epstopdf $ofile
    
    echo $0: output in $ofile
    if [ $gv -eq 1 ];then
	gv $ofile &
    fi
    rm tomo.*.grd  model.*.grd 2> /dev/null
done
