#!/bin/bash
mode=${1-2}
alpha=${2-30}

inc=-I0.05
reg=-R0/10/-10/10

calc_cornerflow $mode $alpha > tmp.dat


gawk '{print($1,$2,$5)}' tmp.dat | xyz2grd $reg $inc -Gtmp.phi.grd -V
gawk '{print($1,$2,$4)}' tmp.dat | xyz2grd $reg $inc -Gtmp.vx.grd -V
gawk '{print($1,$2,$3)}' tmp.dat | xyz2grd $reg $inc -Gtmp.vy.grd -V


#ofile=corner.$mode.$alpha.ps
ofile=corner.ps
proj=-Jx.5

grd2cpt tmp.phi.grd -Cpolar -E21 > tmp.cpt 

grdimage tmp.phi.grd $reg $proj -K -P -Ctmp.cpt > $ofile
grdvector tmp.vx.grd tmp.vy.grd -Gorange -W0.5 \
	  -I1 $reg $proj -T -O -K -Q0.02/0.1/0.04n.2 -S10 >> $ofile
psbasemap $reg $proj -Ba2f.2:"x":/a2f.2:"y":WesN -O  >> $ofile


rm tmp.*
