#!/bin/bash
#
# given a grid with positive values (e.g. 1 vs. NAN or zero), find the centroid location
#

if [ ! -s $1.grd ];then
    f=$1
else
    f=$1.grd
fi
weigh_by_val=${2-1}

if [ ! -s $f ];then
    echo $0: $f not found > "/dev/stderr"
    exit
fi
if [ $weigh_by_val -eq 1 ];then
    grd2xyz $f -S | gawk '{if($3>0)print($1,$2,$3)}' | gawk -f lonlat2xyz.awk | \
	gawk '{print($4,$1,$2,$3)}' | gawk -f wmean.awk | gawk -f xyz2lonlat.awk | gawk '{print($1,$2)}'
else
    grd2xyz $f -S | gawk '{print($1,$2)}' | gawk -f lonlat2xyz.awk | \
	 gawk -f meanallcol.awk | gawk -f xyz2lonlat.awk | gawk '{print($1,$2)}'

fi
