#!/bin/bash
#
# calculate a log mean of grd file
#
if [ $# -lt 1 ];then
	echo `basename $0`: usage: `basename $0` data.grd 
	exit
fi
if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo $1 or $1.grd are nonexistent.
	exit
    fi
fi

gmtset D_FORMAT %20.15e
grdmath $name LOG = tmp.$$.grd
echo `grdinfo -L2 -C tmp.$$.grd | gawk '{printf("%20.15e",exp($12))}'`
rm tmp.$$.grd
gmtset D_FORMAT %lg
