#!/bin/bash
#
# determine median value of data on a geographic grid by roughly even area 
# sampling
#
# usage:
#
# grd2geo_median file.grd  [gridding, reg]
#
#
#

pname=`basename $0`
if [ $# -lt 1 ];then
	echo $pname: usage: $pname file.grd  > "/dev/stderr"
	echo $pname: where the median of file.grd will be computed > "/dev/stderr"
	exit
fi
#
#
gridding=${2-reg}		# order for global (e.g. 10), or "reg"

tmpn=/tmp/$$.$USER.geomean
trap "rm -f $tmpn*; exit" 0 1 2  15
#
#
# check if first grid file exists
#
#
if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo `basename $0`: $1 or $1.grd are nonexistent > "/dev/stderr"
	exit
    fi
fi
if [ $gridding = reg ];then
    grd2reg $name | gawk -f reg2wesn.awk > $tmpn.par
    read w e s n < $tmpn.par
    gawk -v i=11 -v xmin=$w -v xmax=$e -v ymin=$s -v ymax=$n -f even_area_sample.awk  | \
	grdtrack -nl -fg -G$name -Z  -s | gawk -f median.awk
else				# global
    zcat  $datadir/sphere_points/npoints.$gridding.lonlat.gz | \
	grdtrack -nl -fg -G$name -Z  -s | gawk -f median.awk
fi






