#!/bin/bash
if [ $# -eq 0 ];then
    echo usage:
    echo 
    echo $0 file.grd
    echo
    exit
fi
if [ -s $1 ];then
    name=$1
else
    if [ -s $1.grd ];then
	name=$1.grd
    else
	echo $1 or $1.grd are nonexistent.
	exit
    fi
fi

grdinfo -C $name | gawk '{print(($2+$3)/2)}'
