#!/bin/bash
#
# plot a traction vector field at the base of the lithospher
# given as phi and theta components, changed to lithospheric
# driving forces
pquakes=0
threeplots=0
vecinc=10
vecsize='-Q0.01/0.04/0.03'
#check for files
vp=${1-tp.grd}
vt=${2-tt.grd}
vr=${3-tr.grd}
psfile=`echo $vp | gawk '{print(substr($1,1,length($1)-4))}'`.force.ps
if [ -s $vp ]
then 
    if [ -s $vt ]
    then
	echo $0: phi component: $vp 
	echo $0: theta component: $vt
    else
	echo $0: can not find $vt
	exit
    fi
else
    echo $0: can not find $vp
    exit
fi
tmpn=/tmp/$USER.$HOST.plotvelocities
# three different projections, last two only if threeplots is set
reg='-R0/360/-70/70'
# convenient viewing
proj='-JM7 -P'
# full page
#proj='-JM9'
ann=-Ba60f15/a30f15
offset1='-X0.75 -Y0.5'
reg2='-R0/360/-90/90'
proj2='-JH180/6 -P'
offset2='-X1.5 -Y4.5'
reg3='-R0/360/-90/90'
proj3='-JH0/6 -P'
offset3='-X-2 -Y3'


grdmath $vp $vt R2 SQRT = $tmpn.$vp.tmp.abs
max=`grd2max $tmpn.$vp.tmp.abs`
rm $tmpn.$vp.tmp.abs

scaling=`echo $max | gawk '{print(1*$1)}'`
echo $0: absolute maximum is $max, scaling $scaling

#mapping 
# draw coastlines and plate boundaries for first plot
#pscoast $reg $proj -K -G200/200/200 -A70000 -Dc -Ba60/a30:."max $max":  $offset1 > $psfile

if [ -s $vr ]
then
    echo $0: using $vr as background
    makecpt -T-5/5/0.5 -Cjet > $tmpn.tmp.cpt
    grdmath $vr $scaling DIV = $tmpn.tmp.vr.grd
    grdimage $tmpn.tmp.vr.grd -C$tmpn.tmp.cpt $ann $reg $proj -K $offset1 > $psfile
    rm $tmpn.tmp.cpt $tmpn.tmp.vr.grd
    pscoast $reg $proj -K -O -W3/200/200/200  -Dc -A70000  >> $psfile
else
    pscoast $reg $proj -K -G200/200/200  -Dc   -A70000 $offset1 > $psfile
fi


psxy $HOME/tcltk/igmt_develop/nuvel.yx -:   \
	    -M $reg $proj  -O -K   -W.25/0/0/255  >> $psfile
if [ $pquakes -eq 1 ]
then
    gawk '{if(($1!="#")&&($1!=""))print($7,$6,$9*0.0005*8.5)}' \
	 /wrk/arthur/becker/global_data/quakes/usgs_neic.dat | \
	  psxy  $reg $proj -O  -G255/0/255  -K -Sc   >> $psfile
fi
#
#
grdmath $vp 1 MUL = $tmpn.$vp.vy.grd
grdmath $vt -1 MUL  = $tmpn.$vt.vy.grd
#
if [ $threeplots -eq 1 ]
then
    # two other projections
	grdvector $tmpn.$vp.vy.grd $tmpn.$vt.vy.grd -T \
		$reg $proj -I$vecinc $vecsize -S$scaling -G255/0/0 -O -K >> $psfile
	pscoast $reg2 $proj2 -K -O -G200/200/200 -A70000 -Dc  $offset2 >> $psfile
	psxy /home/becker/tcltk/igmt_develop/nuvel.yx -:   \
		    -M $reg2 $proj2 -O -K   -W.25/0/0/255  >> $psfile
	grdvector $tmpn.$vp.vy.grd $tmpn.$vt.vy.grd   -T \
		$reg2 $proj2 -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile

	pscoast $reg3 $proj3 -K -O -G200/200/200 -A70000 -Dc   $offset3 >> $psfile
	psxy /home/becker/tcltk/igmt_develop/nuvel.yx -:   \
		    -M $reg3 $proj3 -O -K   -W.25/0/0/255  >> $psfile
	grdvector $tmpn.$vp.vy.grd $tmpn.$vt.vy.grd   -T \
		$reg3 $proj2 -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile
	echo 40 -65 10 0 0 0 0 "10 cm/yr" | psvelo -S`echo $scaling | gawk '{print(1/$1)}'`/0.95/12 \
	    -G255/0/255 -W6/255/0/255 -O $reg $proj >> $psfile
		
else

	# only one
#	grdvector $tmpn.$vp.vy.grd $tmpn.$vt.vy.grd  -T \
#		$reg $proj -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile
	grdvector $tmpn.$vp.vy.grd $tmpn.$vt.vy.grd -E  -T \
		$reg $proj -I$vecinc $vecsize -Sl0.2 -G255/0/0 -O  -K >> $psfile

	echo 40 -65 1e7 0 0 0 0 "10 MPa" | psvelo -Se`echo $scaling | gawk '{print(1/$1)}'`/0.95/12 \
	    -G255/0/255 -W6/255/0/255 -O $reg $proj >> $psfile


fi
rm  $tmpn.$vt.vy.grd
#ps2epsi $psfile $tmpn.ps
#mv $tmpn.ps $psfile
echo $0: output in $psfile
