#!/bin/bash
tmpn=/tmp/$USER.plvel.$$.$$
trap "rm -f $tmpn.* ; exit" 0 1 2  15

infile=${1-tmp.xyvxvy}
if [ ! -s $infile ];then
    echo $0: can not find $infile
    exit
else
    echo $0: reading from $infile
fi
inc=-I${2-2}
reg=-R0/360/-90/90

awk '{print($1,$2,$3)}' $infile | \
    surface -T1 $reg $inc -G$tmpn.vx.grd
awk '{print($1,$2,$4)}' $infile | \
    surface -T1 $reg $inc -G$tmpn.vy.grd
plotvelocities $tmpn.vx.grd $tmpn.vy.grd
mv $tmpn.vx.ps $infile.ps
