#!/bin/bash
# plot data and model fit for spotted data
model=${1-pmFsteind}
region=${2-42}
type=${3-s.1}
# model
mf=$model/results/spotted/$region/tracer.f.s.es.avg.$type.edr.dat.gz
# data
df=$datadir/splitting/selected.$region.table.dir

tmpn=/tmp/$USER.$HOST.$$.pstr
trap "rm -f $tmpn.* ; exit" 0 1 2  15
# unpack
cp $df $tmpn.data
zcat $mf > $tmpn.model

paste $tmpn.data $tmpn.model | \
    gawk '{if($1!=$4||$2!=$5){print("error, location differ") > "/dev/stderr";}else{\
	a[1]=$3;a[2]=$6;for(i=1;i<=2;i++){\
	    while(a[i]<-180)a[i]+=180.0;\
	    while(a[i]>180)a[i]-=180;}\
	print($1,$2,a[1],a[2],a[2]-a[1])}}' > $tmpn.dat
reg=`minmax -I1 $tmpn.dat`
minmax -C $tmpn.dat
proj=-JM5
# output 
of=$HOME/tmp/$model.$region.$type.colormisfit.ps
length=0.2
size=0.15
pscoast $reg $proj -Dh -G200 -K -Ba5f1WesN -P > $of
# data
awk '{print($1,$2,$3,l)}' l=$length $tmpn.dat | \
    mypsxy $reg $proj -SV-0.03/0/0 -G0 -K -O >>  $of
# model
awk '{print($1,$2,$4,l)}' l=$length $tmpn.dat | \
    mypsxy $reg $proj -SV-0.03/0/0 -G255 -W0.2 -K -O >>  $of
# clockwise overshoot
awk '{if($5>14)print($1,$2,s)}' s=$size $tmpn.dat | \
    psxy -Sc $reg $proj -G200/0/0 -W1 -O -K >> $of
# counterclockwise overshoot
awk '{if($5<-14)print($1,$2,s)}' s=$size $tmpn.dat | \
    psxy -Sc $reg $proj -G0/0/200 -W1 -O -K >> $of
awk '{if(($5>=-14)&&($5<=14))print($1,$2,s)}' s=$size $tmpn.dat | \
    psxy -Sc $reg $proj -G255 -W1 -O  >> $of
modifybb $of 40 50 460 510
echo $0: output in $of
ghostview $of
