#!/bin/bash
#
# plot a pdf or ps file of a GMT colorscale
#
# $Id: showcpt,v 1.2 2002/11/22 02:31:36 becker Exp becker $
#
if [ $# -eq 0 ];then
    echo $0: usage:
    echo $0: `basename $0` colorscale.cpt
    exit
fi
if [ ! -s $1 ]
then
	c=$1.cpt
else
	c=$1
fi
if [ ! -s $c ]
then
	echo $0: colomap $c does not exist
	exit
fi
labs=${2--1}			# label, -1: use original
title=${3-""}
units=${4-""}
withends=${5-0} # 0: no 1: both -1: left -2: right
portrait=${6-1} 
pdf=${7-0}

echo $0: colorscale: $c
echo $0: labels: $labs
echo $0: title: $title
echo $0: units: $units
echo $0: with ends: $withends
echo $0: portrait: $portrait
echo $0: pdf: $pdf

if [ $portrait -eq 1 ];then
    bb="160 10 470 75"
    size=3.0/0.0/3/0.3h
    proj="-JX6"
    off=-Y1.5
else
    bb="265 60 460 530"
    size=3.0/0.0/3/0.3
    proj="-JX6 -Y4"
fi
#if [ $pdf -eq 1 ];then
#    gmtset BASEMAP_FRAME_RGB 255/255/255
#fi
psfile=`echo $c | \
 gawk '{printf("%s.eps",substr($1,1,length($1)-4))}'`
pdffile=`echo $c | \
 gawk '{printf("%s.pdf",substr($1,1,length($1)-4))}'`



echo 100 100 1 | psxy -R0/1/0/1 $proj -P -Sa -K $off > $psfile
if [ `echo $labs | \
      gawk '{if($1==-1)print(1);else print(0)}'` -eq 1 ];then
    ann=-B:"$title":/:"$units": 
else
    ann=-B$labs:"$title":/:"$units":
fi
echo $ann

if [ $withends -eq 1 ];then
    psscale -C$c  -N50 -D$size  "$ann"  -E  -O >> $psfile
elif [ $withends -eq 2 ];then
    psscale -C$c  -N50 -D$size  "$ann"  -E-  -O >> $psfile
elif [ $withends -eq 3 ];then
    psscale -C$c  -N50 -D$size  "$ann"  -E+  -O >> $psfile
else
   psscale -C$c  -N50 -D$size $ann  -O >> $psfile
fi
if [ ! -s $psfile ];then
    echo $0: error, no ps file produced
    exit
fi
#modifybb $psfile $bb
modifybb $psfile 
if [ $pdf -eq 1 ];then
    epstopdf $psfile 
    rm $psfile
    echo $0: output in $pdffile
else
    echo $0: output in $psfile 
fi


#gmtset BASEMAP_FRAME_RGB 0/0/0
