#!/bin/bash
#
# plot a vector field that is given as x and y components
#
pquakes=0
threeplots=0
vecinc=10
vecsize='-Q0.01/0.04/0.03'
#check for files
vx=${1-vx.grd}
vy=${2-vy.grd}
vr=${3-vr.grd}
psfile=`echo $vx | gawk '{print(substr($1,1,length($1)-4))}'`.ps
if [ -s $vx ]
then 
    if [ -s $vy ]
    then
	echo $0: using x component: $vx 
	echo $0: and   y component: $vy
    else
	echo $0: can not find $vy
	exit
    fi
else
    echo $0: can not find $vx
    exit
fi
tmpn=/tmp/$USER.$HOST.$$.plotvelocities
trap "rm -f $tmpn.* ; exit" 0 1 2  15
# three different projections, last two only if threeplots is set
reg='-R0/360/-70/70'
# convenient viewing
proj='-JM7 -P'
# full page
#proj='-JM9'
ann=-Ba60f15/a30f15
offset1='-X0.75 -Y0.5'
reg2='-R0/360/-90/90'
proj2='-JH180/6 -P'
offset2='-X1.5 -Y4.5'
reg3='-R0/360/-90/90'
proj3='-JH0/6 -P'
offset3='-X-2 -Y3'


grdmath $vx $vy R2 SQRT = $tmpn.abs
max=`grd2max $tmpn.abs`


scaling=.9
echo $0: absolute maximum is $max, scaling fixed at $scaling

#mapping 
# draw coastlines and plate boundaries for first plot
#pscoast $reg $proj -K -G200/200/200 -A70000 -Dc -Ba60/a30:."max $max":  $offset1 > $psfile

if [ -s $vr ]
then
    echo $0: using $vr as background
    makecpt -T-5/5/0.5 -Cjet > $tmpn.tmp.cpt
    grdmath $vr $scaling DIV = $tmpn.tmp.vr.grd
    grdimage $tmpn.tmp.vr.grd -C$tmpn.tmp.cpt $ann $reg $proj -K $offset1 > $psfile
    rm $tmpn.tmp.cpt $tmpn.tmp.vr.grd
    pscoast $reg $proj -K -O -W3/200/200/200  -Dc   >> $psfile
else
    pscoast $reg $proj -K -G200/200/200  -Dc   $ann $offset1 > $psfile
fi


psxy $HOME/tcltk/igmt_develop/nuvel.yx -:   \
	    -M $reg $proj  -O -K   -W.25/0/0/255  >> $psfile
if [ $pquakes -eq 1 ]
then
    gawk '{if(($1!="#")&&($1!=""))print($7,$6,$9*0.0005*8.5)}' \
	 /wrk/arthur/becker/global_data/quakes/usgs_neic.dat | \
	  psxy  $reg $proj -O  -G255/0/255  -K -Sc   >> $psfile
fi
if [ $threeplots -eq 1 ]
then
    # two other projections
	grdvector $vx $vy -T \
		$reg $proj -I$vecinc $vecsize -S$scaling -G255/0/0 -O -K >> $psfile
	pscoast $reg2 $proj2 -K -O -G200/200/200 -A70000 -Dc  $offset2 >> $psfile
	psxy /home/becker/tcltk/igmt_develop/nuvel.yx -:   \
		    -M $reg2 $proj2 -O -K   -W.25/0/0/255  >> $psfile
	grdvector $vx $vy  -T \
		$reg2 $proj2 -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile

	pscoast $reg3 $proj3 -K -O -G200/200/200 -A70000 -Dc   $offset3 >> $psfile
	psxy /home/becker/tcltk/igmt_develop/nuvel.yx -:   \
		    -M $reg3 $proj3 -O -K   -W.25/0/0/255  >> $psfile
	grdvector $vx $vy   -T \
		$reg3 $proj2 -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile
	echo 40 -65 1 0 0 0 0 "1 cm/yr" | psvelo -S`echo $scaling | gawk '{print(1/$1)}'`/0.95/12 \
	    -G255/0/255 -W6/255/0/255 -O $reg $proj >> $psfile
		
else

	# only one
	grdvector $vx $vy  -T \
		$reg $proj -I$vecinc $vecsize -S$scaling -G255/0/0 -O  -K >> $psfile

	echo 40 -65 .1 0 0 0 0 ".1 cm/yr" | psvelo -Se`echo $scaling | gawk '{print(1/$1)}'`/0.95/12 \
	    -G255/0/255 -W6/255/0/255 -O $reg $proj >> $psfile


fi
ps2epsi $psfile $tmpn.ps
mv $tmpn.ps $psfile
echo $0: output in $psfile
